'''
Project Euler - Problem 2
http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''


def fibsum1(upper):
    m = 1
    n = 0
    o = 0
    sum = 0
    while m < upper:
        o = n
        n = m
        m = o + m
        if m % 2 == 0:
            sum += m
    return sum

print fibsum1(4000000)
